### PR TITLE
Add support for specifying lodash targets and support for multiple targets in lodashAutobuild 

### LINKED ISSUE #2: Add config option to specify lodash targets to run
Another suggestion is to add a configuration option to run a specific lodash target instead of all of them. The last line of grunt-lodash-autobuild executes all lodash targets:

``` javascript
grunt.task.run('lodash')
```

My lodash config looks like this:

``` javascript
    lodash: {
      build: {
        dest: 'app/vendor/lodash.build.js',
        options: {
          exports: ['amd'],
          flags: [
            '--debug'
          ]
        }
      },
      test: {
        dest: 'tests/vendor/lodash.full.js',
        options: {
          exports: ['amd'],
          flags: [
            '--debug'
          ]
        }
      }
    },
    lodashAutobuild: {
      src: ['app/js/**/*.js'],
      options: {
        lodashConfigPath: 'lodash.build.options.include',
        lodashObjects: [ '_' ]
      }
    },
```

In my app, Grunt is configured to rebuild `lodash.build.js` during a watch task, whenever any `app/**/*.js` files are changed. 

I'd prefer to not waste time rebuilding the full version of lodash for my tests. I want a different watch task to do that when any test files change.

### PR DESCRIPTION
**Pull request by tauren**
This should resolve #2.

### CODE REVIEW

**Comment by jjt** [comment]
Cool, looks good on first glance. I'll take a better look tomorrow.

**Comment by tauren** [comment]
Any chance you could get this pulled in soon?

**Comment by jjt** [comment]
Sorry, some urgent stuff popped up. Should have some time later today.

**Comment by jjt** [comment]
Great, thanks again!

**Comment by tauren** [comment]
Thanks so much for getting this pulled in! Makes it easier for others on my team to use the changes we need.

**Comment by jjt** [comment]
No problem, I'm glad it's useful to you.

**Pull request merged**
